
name: Rust

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        toolchain:
          - stable
          - nightly
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install latest Rust Nightly
      id: actions-rs
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: LFS Checkout
      run: git lfs checkout
    - name: Version
      run: rustc -Vv
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose -- --test-threads=1 --nocapture
